// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: knockknock.proto

package knockknock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the count and wait time.
type KnockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Wait  int32 `protobuf:"varint,2,opt,name=wait,proto3" json:"wait,omitempty"`
}

func (x *KnockRequest) Reset() {
	*x = KnockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knockknock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnockRequest) ProtoMessage() {}

func (x *KnockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knockknock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnockRequest.ProtoReflect.Descriptor instead.
func (*KnockRequest) Descriptor() ([]byte, []int) {
	return file_knockknock_proto_rawDescGZIP(), []int{0}
}

func (x *KnockRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *KnockRequest) GetWait() int32 {
	if x != nil {
		return x.Wait
	}
	return 0
}

// The response message
type KnockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *KnockReply) Reset() {
	*x = KnockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knockknock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnockReply) ProtoMessage() {}

func (x *KnockReply) ProtoReflect() protoreflect.Message {
	mi := &file_knockknock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnockReply.ProtoReflect.Descriptor instead.
func (*KnockReply) Descriptor() ([]byte, []int) {
	return file_knockknock_proto_rawDescGZIP(), []int{1}
}

func (x *KnockReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_knockknock_proto protoreflect.FileDescriptor

var file_knockknock_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x22, 0x38,
	0x0a, 0x0c, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x77, 0x61, 0x69, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x4b, 0x6e, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x47, 0x0a, 0x04, 0x44, 0x6f, 0x6f, 0x72, 0x12, 0x3f, 0x0a, 0x05, 0x4b, 0x6e, 0x6f, 0x63,
	0x6b, 0x12, 0x18, 0x2e, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x2e, 0x4b,
	0x6e, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6b, 0x6e,
	0x6f, 0x63, 0x6b, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x2e, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x33, 0x35, 0x79, 0x73, 0x68, 0x72, 0x2f,
	0x67, 0x52, 0x50, 0x43, 0x5f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x6b, 0x6e, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_knockknock_proto_rawDescOnce sync.Once
	file_knockknock_proto_rawDescData = file_knockknock_proto_rawDesc
)

func file_knockknock_proto_rawDescGZIP() []byte {
	file_knockknock_proto_rawDescOnce.Do(func() {
		file_knockknock_proto_rawDescData = protoimpl.X.CompressGZIP(file_knockknock_proto_rawDescData)
	})
	return file_knockknock_proto_rawDescData
}

var file_knockknock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_knockknock_proto_goTypes = []interface{}{
	(*KnockRequest)(nil), // 0: knockknock.KnockRequest
	(*KnockReply)(nil),   // 1: knockknock.KnockReply
}
var file_knockknock_proto_depIdxs = []int32{
	0, // 0: knockknock.Door.Knock:input_type -> knockknock.KnockRequest
	1, // 1: knockknock.Door.Knock:output_type -> knockknock.KnockReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_knockknock_proto_init() }
func file_knockknock_proto_init() {
	if File_knockknock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_knockknock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knockknock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_knockknock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knockknock_proto_goTypes,
		DependencyIndexes: file_knockknock_proto_depIdxs,
		MessageInfos:      file_knockknock_proto_msgTypes,
	}.Build()
	File_knockknock_proto = out.File
	file_knockknock_proto_rawDesc = nil
	file_knockknock_proto_goTypes = nil
	file_knockknock_proto_depIdxs = nil
}
